### ISSUE TITLE
Has the project died?

### ISSUE THREAD

**Issue by marksev1** [klec00/MMM-mqtt-monitor#1]
I'd be super-interested in this module, but there hasn't been any developement?

**Comment by klec00** [comment]
The idea was to generate a generalized MQTT listener that other modules
could subscribe from, similar to what the MMM calendar module provides.
The MQTT code is available in the module
https://github.com/klec00/MMM-Timetable-mqtt so it shouldn't be too
difficult to make it work. unfortunately lack of time has prevented a
further development as of now.

2017-02-16 10:12 GMT+01:00 marksev1 <notifications@github.com>:

**Comment by marksev1** [comment]
Looking forward, if it will be maybe continued in the future (it would be super-useful for home automation users).
